version: '3.8'

services:
  bdd:
    image: jorgearmijo882/bdd-app:latest
    container_name: bdd
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: devops_tfm
      POSTGRES_USER: tfm_user
      POSTGRES_PASSWORD: tfm_pass
    restart: always

  backend:
    image: jorgearmijo882/backend-app:latest
    container_name: backend
    ports:
      - "8081:8080"
    depends_on:
      - bdd
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bdd:5432/devops_tfm
      SPRING_DATASOURCE_USERNAME: tfm_user
      SPRING_DATASOURCE_PASSWORD: tfm_pass
    restart: always

  frontend:
    image: jorgearmijo882/frontend-app:latest
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always