trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerHubRepo: 'jorgearmijo882/frontend-app'
  imageTag: 'latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub-connection'
    repository: '$(dockerHubRepo)'
    command: 'buildAndPush'
    Dockerfile: 'docker/frontend/Dockerfile'
    tags: |
      $(imageTag)